### ISSUE TITLE
Cartel convocatoria

### ISSUE THREAD

**Issue by flowsta** [medialab-prado/diadatosabiertos2017#12]
Podemos hacer un cartel para la convocatoria. Podemos utilizar gráfica ya existente:

- Logo ODD Madrid
- Gráfica web opendataday.org

Elementos de la web:
- Título: Día de los Datos Abiertos 2017
- Subtítulo: Madrid Abriendo Datos
- Texto: lo que se pueda de la convocatoria
- Agenda: extracto de la convocatoria
- Organizan: (con los logos)
 - Medialab-Prado
 - ODI-Madrid

**Comment by mariapoveda** [comment]
¿Hay enlace a esto? "Agenda: extracto de la convocatoria"

**Comment by mariapoveda** [comment]
Banner https://github.com/okfn/opendataday/tree/master/assets/images
Logo generator: http://odd.structure-and-representation.com/
Información y estructura: http://opendataday.org/es_es/

El logo de EDP tiene que aparecer.
Organizan: (con los logos): MediaLab Prado, ODI Madrid, EDP ¿alguno más?
