### ISSUE TITLE
¿Readme.org?

### ISSUE THREAD

**Issue by ajspadial** [medialab-prado/diadatosabiertos2017#3]
¿Hay algún motivo para este archivo tenga un nombre de dominio como extensión?

Me parece un poco raro y hasta contradictorio con el objetivo de la jornada.

Sugerencias:
* `README`  
* `README.md`  
* `README.txt`

O cualquier alternativa con `LEEME`

**Comment by flowsta** [comment]
.org es la extensión de los archivos org-mode, sintaxis utilizada para el Readme

**Comment by ajspadial** [comment]
Gracias. Suponía que había algo que no sabía.
